### ISSUE TITLE
release 0.0.3 - fails on -  lxdev template create guitemplate --profile gui --provisioners vscode

### ISSUE THREAD

**Issue by bmullan** [bketelsen/dlx#14]
$ **lxdev version**
**0.0.3**

$ **lxdev config -c**
~ Create configuration
✓ Default configuration file created
✓ Configuration created

bmullan@dadspc:~$ **lxdev config -t**
~ Create configuration
✓ Templates created
✓ Configuration created

bmullan@dadspc:~$ **lxdev profile -w gui**
~ Managing profile gui
~ Creating profile gui
✓ Creating profile gui
✓ Managing profile gui

bmullan@dadspc:~$ **lxdev profile -w cli**
~ Managing profile cli
~ Creating profile cli
✓ Creating profile cli
✓ Managing profile cli

bmullan@dadspc:~$ **lxdev template create guitemplate --profile gui --provisioners vscode**
~ Creating template guitemplate
**_✗ Unable to create template: waiting for container start: Common start logic: Missing parent 'enp5s0' for nic 'eth0'_**

I don't know the interpretation of the above message about -  **Missing parent 'enp5s0'** but my "host" system uses WiFi for internet/network access and not ethernet.   But that message may not have anything to do with that as I realize the reference to "enp5s0' could be for an interface "inside" the container.

> $ ifconfig
> enp10s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         ether 08:60:6e:87:a8:58  txqueuelen 1000  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 728370  bytes 282712698 (282.7 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 728370  bytes 282712698 (282.7 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lxdbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         inet 10.105.172.1  netmask 255.255.255.0  broadcast 0.0.0.0
>         inet6 fe80::d04e:e6ff:fe04:db22  prefixlen 64  scopeid 0x20<link>
>         ether 00:00:00:00:00:00  txqueuelen 1000  (Ethernet)
>         RX packets 422055  bytes 281775857 (281.7 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 361640  bytes 131269725 (131.2 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
>         ether 52:54:00:58:bc:68  txqueuelen 1000  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> **wlxc8d719c17a3d**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.1.130  netmask 255.255.255.0  broadcast 192.168.1.255
>         inet6 fe80::55f4:b889:ffdc:500b  prefixlen 64  scopeid 0x20<link>
>         ether c8:d7:19:c1:7a:3d  txqueuelen 1000  (Ethernet)
>         RX packets 533271  bytes 640898273 (640.8 MB)
>         RX errors 0  dropped 38  overruns 0  frame 0
>         TX packets 185614  bytes 31731616 (31.7 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ChristianBoehm** [comment]
that's caused why your hosts machine network adapter is not enp5s. You should adjust according to your needs inside ~/.lxdev/profiles => gui.yaml and cli.yaml. But unfortunately macvlan doesn't work with wifi. For more information see here [https://blog.simos.info/how-to-make-your-lxd-container-get-ip-addresses-from-your-lan/](url) Warning 1. You should try in bridged mode, I suggest try to remove eth0 section in gui.yaml and cli.yaml and test again.

**Comment by bmullan** [comment]
Christian
Thanks... but I already know macvlan doesn't work with wifi.   

What I didn't know was weather the mention of "enp5s" was concerning some internal container config or not.

I also didn't know where to even look to address the problem.

I guess since many people use WiFi... this will need to be looked at by the LXDEV author Brian Ketelson sometime in the future as to addressing it during installation. and maybe altering LXDEV to support a WiFi connected host.

Thanks for your info tho'.
Brian Mullan

**Comment by bmullan** [comment]
Ok... 
changed gui.yaml to:

> config:
>   environment.DISPLAY: :0
>   security.devlxd: false
>   raw.idmap: both 1000 1000
>   raw.lxc: |
>     lxc.apparmor.profile=unconfined
>     lxc.mount.auto=proc:rw sys:rw
>     lxc.cap.drop=
>   security.nesting: "true"
>   security.privileged: "true"
> 
> description: GUI LXD profile
> devices:
>   eth0:
>     nictype: bridged
>     parent: lxdbr0
>     type: nic
>   PASocket:
>     path: /tmp/.pulse-native
>     source: /run/user/1000/pulse/native
>     type: disk
>   X0:
>     bind: container
>     connect: unix:@/tmp/.X11-unix/X0
>     listen: unix:@/tmp/.X11-unix/X0
>     security.gid: "1000"
>     security.uid: "1000"
>     type: proxy
>   mygpu:
>     type: gpu
> name: gui
> used_by

then...

> $ lxdev profile -w gui

then... this succeeded...

> $ lxdev template create guitemplate --profile gui --provisioners vscode

Then I was able to create a container and shell into it...

Brian Mullan

**Comment by ChristianBoehm** [comment]
:) nice that's what I suggest. The only one exception you can't ssh direct into your container via local lan ip. You can figure out containers ip with `ip address show` from a container shell.

**Comment by bmullan** [comment]
Of course since ssh server is installed in the container if you've edited /etc/ssh/sshd_config and changed the following to:

- _PermitRootLogin no_
- _PasswordAuthentication yes_
- _ChallengeResponseAuthentication yes_

then
# service ssh restart

Then from the host you can just do:

> **$ lxc list <cn name> to get the ip**
> **$ ssh userID@that_IP

But again, thanks for your help pointing me to what to change to get the guitemplate to work.  I just wasn't sure where to look to make the edits.

**Comment by bketelsen** [comment]
Is there a reliable way to get the name of the interface that's used for networking?
We could make the profiles a template that gets written instead of just doing a file copy, substituting the proper adapter name.

**Comment by bmullan** [comment]
@bketelsen 
Yes this script could tell you whether the Host's internet device is ethernet or not.  You'd have to adapt it a little do do an IF/ELSE comparison but

> #/bin/bash
> net_device=$(ip route get 8.8.8.8 | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
> echo $net_device

try it on in a terminal and you'll see the output

What its doing is issuing the "ip route get" to googles 8.8.8.8 DNS server and the response is normally something like:

example for wifi:
8.8.8.8 via 192.168.1.1 dev **wlxc8d719c17a3d** src 192.168.1.130 uid 1000 

example for ethernet:
8.8.8.8 via 192.168.1.1 dev **enp5s** src 192.168.1.130 uid 1000 

in my little script the $(ip route get 8.8.8.8 | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
just retrieves the next field of text after the word "dev "

So in Brian in your script you could use something like my little script then add an additonal test to see if the first letters of $net_device are "enp" since in ubuntu all ethernet devices in a Host are listed as "enpxxxxx" I believe.

If it matches then you know you have a Host with an Ethernet Internet connection.
If it doesn't, its a Host with a WiFi Internet connection.

I'd think that should work, right ?

Brian Mullan

**Comment by bmullan** [comment]
@bketelsen 
I do have a question though... is there a reason you just don't use LXDBR0 for instead of macvlan?

The containers still get access to the internet.   They can also still access the Host just by connecting to the 10.x.x.1 network address of the LXDBR0 bridge subnet as 10.x.x.1 is the IP address of the Host connection to the LXDBR0 bridge.

But perhaps you are using macvlan so the containers get an assigned IP address on the host's network for some reason.

Just beware that using macvlan like that will mean that is fine except in environments like AWS EC2 cloud where only your host is given an IP address from AWS, same with Digital Ocean cloud and Hetzner's cloud.   Not sure about Azure because I've not used it.

Of course on all those clouds you can pay a small/trivial amount to get an 'elastic IP address" which then you can configure manually but I'd imagine alot of folks using LXDEV would like to avoid that if they were wanting to use LXDEV on an ubuntu server instance on one of those clouds?

Just a thought.
