### ISSUE TITLE
using host SSH-agent

### ISSUE THREAD

**Issue by moonmeister** [bketelsen/dlx#27]
If we mount the unix socket for the ssh-agent on the host into the LXD container then the host can be the source of truth for the container ssh. SSH_AUTH_SOCK enables us to dynamically set this. 

This allows not copying .ssh files into new containers and will enable support for yubikeys/gpg keys through `gpg-agent`.

More info:
https://discuss.linuxcontainers.org/t/how-to-mount-the-ssh-agent-socket-into-lxd-container/2591/3

I intend to work on this at some point but if anyone else wants to please do...though this might be dependent on #24

**Comment by bketelsen** [comment]
great idea!
