### ISSUE TITLE
delete infers stop?

### ISSUE THREAD

**Issue by flowchartsman** [bketelsen/dlx#8]
A brief look at the code looks like you need to call stop before you call delete, so inferring stop from delete might be good.

**Comment by bketelsen** [comment]
You do need to stop a container before you can delete it.  I wasn't sure about "principle of least surprise" here, since I might not remember I have the container running?  I think it's probably ok to try the close first, but would certainly appreciate other opinions on it.

**Comment by bketelsen** [comment]
I think the right answer here is to prompt for confirmation when deleting a running container.
